### PR TITLE
PR: Fix tests

### LINKED ISSUE #45: Fix testing suite
In https://github.com/Quansight/ibis-vega-transform/pull/41 I broke the tests, we should update the saved SVGs to match what is in master.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #45

### CODE REVIEW

File: test/ui/test.ts [hunk 1]
```diff
@@ -260,6 +260,9 @@ describe('Test Ibis-Vega-Transform', () => {
       );
       console.log(`Setting download folder: ${folderPath}`);
 
+      // Wait to make sure all images appeared
+      await sleep(maxTimeout / 2);
```
Comment (saulshanabrook) [inline test/ui/test.ts]: Nice =P

**Comment by saulshanabrook** [comment]
Wonderful!
